name = "glisbn"
version = "1.0.0"
gleam = ">= 1.0.0"
licences = ["MIT"]
description = "A ISBN utility library for the Gleam"
repository = { type = "github", user = "solar05", repo = "glisbn" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
